def menu_principal():
    print("\nBienvenido al sistema de vacunación de mascotas")
    print("Este programa permite gestionar el registro y vacunación de mascotas")
    print("A continucación Por favor registre los datos de administrador")
    input("Presione ENTER para continuar...")
    print("\n\t\t\t SISTEMA DE VACUNACIÓN")
    print("\nPor favor, seleccione una opción:")
    print("\n1. Acceso Administrador")
    print("2. Acceso Beneficiario") 
    print("3. Registro de Mascotas")
    print("\n4. Salir")
    b = input("Seleccione opción: ")
    return(b)
menu_principal()
